# Generated by Django 3.0.2 on 2020-02-28 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(help_text='В формате XXX-XXX', max_length=9, validators=[django.core.validators.RegexValidator('[0-9]{4}-[0-9]{4}')], verbose_name='Годы жизни'),
        ),
    ]
