# Generated by Django 3.0.2 on 2020-01-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('name',), 'verbose_name': 'Post'},
        ),
    ]
