# Generated by Django 3.0.5 on 2020-04-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200428_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
