# Generated by Django 3.0.2 on 2020-03-24 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200228_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(help_text='В формате XXXX-XXXX', max_length=9, validators=[django.core.validators.RegexValidator('[0-9]{4}-[0-9]{4}', message='Неправильный формат даты')], verbose_name='Годы жизни'),
        ),
    ]
