# Generated by Django 3.0.2 on 2020-03-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200324_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ф.И.О ветерана'),
        ),
    ]
