# Generated by Django 2.2.7 on 2019-11-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veteran',
        ),
    ]
