# Generated by Django 2.2.7 on 2019-11-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_delete_veteran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=9)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
